algoritmo "semnome"
// Função :
// Autor :
// Data : 28/07/2023
// Seção de Declarações 
var

     clienteLan:caracter
     tempoUsado:inteiro
     totalApagar: real

inicio

     escreval("Digite o seu nome")
     leia(clienteLan)
     
     escreval("Tempo usado na lan")
     leia(tempoUsado)
     
     totalApagar <- tempoUsado * 2
     
     
     escreval("Cliente:", clienteLan)
     escreval("Tempo usado:", tempoUSado)
     escreval("Total a pagar:", totalApagar)



fimalgoritmo
