algoritmo "Exercício Enquanto Faca - número for diferente de 5"
// Função :
// Autor :
// Data : 01/08/2023
// Seção de Declarações 
var
        numero, resultado:inteiro
inicio

       resultado <- 0
       Escreval("Digite um número:")
       leia(numero)
       
       Enquanto numero <> 5 Faca
       
         resultado <- resultado + numero
         Escreval("Digite um número:")
         Leia(numero)

       FimEnquanto
       
       Escreval("Total: ", resultado)

fimalgoritmo
