algoritmo "Exercício Repita Ate que imprima 50 números Pares"
// Função :
// Autor :
// Data : 05/08/2023
// Seção de Declarações 
var
    numeroPar, quantidadeVezes: inteiro

inicio

    numeroPar <- 2
    quantidadeVezes <- 1
    
    Repita

        Escreval(numeroPar)
        numeroPar <- numeroPar + 2
        quantidadeVezes <- quantidadeVezes + 1
    
    Ate quantidadeVezes > 50

fimalgoritmo
