algoritmo "Exercício Enquanto Faca número de 1 a 10"
// Função :
// Autor :
// Data : 02/08/2023
// Seção de Declarações 
var

    numero:inteiro

inicio

    Escreval("Digite um número")
    Leia(numero)
    
    Enquanto ( numero < 0 ) ou ( numero > 10 ) Faca

          Escreval("Atenção, você precisa digitar um número de 1 a 10")
          Leia(numero)
    
    FimEnquanto

          Escreval("Correto!!!!")

fimalgoritmo
