algoritmo "semnome"
// Função :
// Autor :
// Data : 28/07/2023
// Seção de Declarações 
var

         numero:inteiro
inicio

         escreval("Digite um número")
         leia(numero)
         
         se ( numero > 10) entao
         
             escreval(numero, " é Maior do que 10.")
         
         senao
         
             escreval(numero, " é Menor do que 10.")
         
         fimse


fimalgoritmo
