algoritmo "Função Se com E"
// Função :
// Autor :
// Data : 29/07/2023
// Seção de Declarações 
var
     numero:inteiro

inicio

     Escreval("Digite um número")
     Leia(numero)
     
     Se ( numero >= 1 )   e  ( numero <= 10 )  Entao
     
        Escreval("O número está no intervalo de 1 a 10")
        
     Senao
     
        Escreval("O número digitado está fora do intervalo entre 1 a 10.")

     FimSe
     

fimalgoritmo
