algoritmo "Função Se com Ou"
// Função :
// Autor :
// Data : 29/07/2023
// Seção de Declarações 
var
     cor:caracter

inicio

     Escreval("Digite uma cor: ")
     Leia(cor)
     
     Se( cor = "azul" ) ou ( cor = "amarela" ) Entao

              Escreval("A cor digitada é Azul ou Amarela")
       
       Senao
       
              Escreval("A cor digitada é inválida")
       
       FimSe
     

fimalgoritmo
