algoritmo "Função Se 2"
// Função :
// Autor :
// Data : 29/07/2023
// Seção de Declarações 
var
      cor:caracter

inicio

       Escreval("Digite uma cor")
       leia(cor)
       
       Se (cor = "Amarelo") Entao
       Escreval("A cor digitada é Amarelo")
       
       Senao
       
       Se (cor = "Azul") Entao
       Escreval("A cor digitada é Azul")
       
       Senao
       Escreval("A cor digitada é inválida")
       
       
       
       FimSe
       FimSe

fimalgoritmo
